spacetelescope/roman_notebooks

notebooks/stips/requirements.txt
notebooks/stips/stips.ipynb

_(Re-do of #17 after the old fork was disconnected from this repository.)_
The previous version of the STIPS notebook does not run without errors, so I have fixed that here and added more explanatory text.
There are a couple of cells that break the PEP8 check but are valid in an interactive context. The test run for commit 67fba8d, where I commented those lines out, shows that the rest of the notebook is PEP8 compliant.
---
Its purpose is to serve as a guide for both the notebook author and the technical reviewer highlighting critical aspects to consider when striving to develop an …

Expand and fix STIPS tutorial

---

notebooks/pandeia/pandeia.ipynb

While the notebook runs, many of the numerical results are different from the [RDox tutorial](https://roman-docs.stsci.edu/simulation-tools-handbook-home/pandeia-for-roman/pandeia-tutorials) from which the examples were derived, so we may need to check on the discrepancies.
Examples:
* "Calculate a scene's signal-to-noise ratio" section
* RDox: 28.2 SNR
* NB: 8.61 SNR
* "Estimate optimal limiting magnitude" section
* RDox: 27.68 magnitude
* NB: 26.29 magnitude
* "Determine optimal number of exposures" section, using mag=27
* RDox: 47 exposures, 20.06 SNR, 26,147.04 second exposure time
* NB: 575 exposures, 20 SNR, 55,861.68 second exposure time
* Note: I changed to mag=26 following an author comment on the RDox page, which gives 95 exposures, 19.98 SNR, 9,148.08 second exposure time
* …

Cleaned up Pandeia tutorial

---

notebooks/data_discovery_and_access/data_discovery_and_access.ipynb
notebooks/data_discovery_and_access/requirements.txt

Updating markdown for data access notebook

---

content/notebooks/stips/stips.ipynb

#24 didn't include this change, so I've added it here.
---

Updated STIPS additional resources

---

content/notebooks/data_discovery_and_access/data_discovery_and_access.ipynb

Switched Data Discovery Example from HST to JWST

---

content/notebooks/romanisim/romanisim.ipynb

Adding separate romanisim notebook with revamped examples

---

content/notebooks/aperture_photometry/aperture_photometry.ipynb
content/notebooks/data_discovery_and_access/data_discovery_and_access.ipynb
content/notebooks/data_visualization/data_visualization.ipynb
content/notebooks/measuring_galaxy_shapes/measuring_galaxy_shapes.ipynb
content/notebooks/pandeia/pandeia.ipynb
content/notebooks/rist/rist.ipynb
content/notebooks/romancal/romancal.ipynb
content/notebooks/romanisim/romanisim.ipynb
content/notebooks/stips/stips.ipynb
content/notebooks/synphot/synphot.ipynb
content/notebooks/webbpsf/webbpsf.ipynb
content/notebooks/working_with_asdf/working_with_asdf.ipynb

Resolve RMO Comments on Notebook Text

---

content/notebooks/measuring_galaxy_shapes/measuring_galaxy_shapes.ipynb

This PR:
- Fixes the Sérsic profile fitting. Fix included computing source flux in units of photons / s / cm^2 and doing a background subtraction.
- Builds out the examples, specifically what happens if we do not know input parameters well. Also improves plotting of models and residuals.
- Improves formatting of code cells and adds more explanation to markdown cells.

Update Measuring Galaxy Shapes Tutorial

---

markdown/simulated-data.md

This PR updates the `simulated-data.md` file. The update includes details about the newly converted Open Universe Roman data in ASDF.

Updated simulated data product descriptions

---

content/notebooks/data_discovery_and_access/data_discovery_and_access.ipynb

Fixing errors from notebook:
- anon=True removed from s3fs calls
- changed dataset example for Open Universe data to a file currently in the bucket
- reverted change to MAST example back to HST/WFC3/IR (not sure how this got changed)
- Added comment to download section about setting the URI variable

Fixing errors

---

content/notebooks/romanisim/romanisim.ipynb
content/notebooks/stips/stips.ipynb

- STIPS visualizations updated to remove LogNorm normalization and replace with vmin / vmax limits.
- Roman I-Sim tutorial moved parallelization example to end of notebook, commented out code cell that runs the simulation, and added a note about runtime. Cell seems to take a very long time to run with current settings.

Sept24 updates

---

content/notebooks/pandeia/pandeia.ipynb

Updating the pandeia notebook

---

content/notebooks/data_discovery_and_access/data_discovery_and_access.ipynb

Added info about AAS_WORKSHOP directory. Removed old directories. Changed example file path for reading in a file from S3.

Updating Data Discovery Notebook Markdown

---

content/notebooks/rist/rist.ipynb

Incorporating RIST notebook comments from RMO in preparing for the AAS workshop

---

content/notebooks/aperture_photometry/aperture_photometry.ipynb
content/notebooks/working_with_asdf/working_with_asdf.ipynb

Fixing data paths and changes to units/quantity objects

Fixes for photometry and working with ASDF

---

.gitignore
content/notebooks/aperture_photometry/aperture_photometry.ipynb
content/notebooks/measuring_galaxy_shapes/measuring_galaxy_shapes.ipynb
content/notebooks/working_with_asdf/working_with_asdf.ipynb

- Markdown updates by @wcschultz for aperture photometry, working with ASDF, and measuring galaxy shapes.
- Code fixes to measuring galaxy shapes to remove the old quantity arrays no longer used in roman_datamodels (and associated markdown update).
- Update gitignore to ignore ASDF and ECSV files

Markdown & Code Fixes

---

content/notebooks/exposure_pipeline/exposure_pipeline.ipynb
content/notebooks/mosaic_pipeline/mosaic_pipeline.ipynb
content/notebooks/romanisim/romanisim.ipynb

- Merge feedback on exposure pipeline markdown
- Merge feedback on mosaic pipeline markdown
- Fix missing os import in mosaic pipeline tutorial
- Merge feedback on parallelized, dithered example in Roman I-Sim tutorial

ELP, MLP, Roman I-Sim Feedback Merges

---

content/notebooks/grism_spectral_extraction/grism_spectral_extraction.ipynb
content/notebooks/mosaic_pipeline/mosaic_pipeline.ipynb

- Fixing bug in mosaic pipeline tutorial S3 get
- Updating spectroscopy notebook part 1. Uploading for RMO to start reviewing.

MLP Bug Fix + Spec Part 1

---

content/notebooks/working_with_asdf/working_with_asdf.ipynb

Workshop fix for working with asdf

---

content/notebooks/exposure_pipeline/exposure_pipeline.ipynb
content/notebooks/measuring_galaxy_shapes/measuring_galaxy_shapes.ipynb
content/notebooks/mosaic_pipeline/mosaic_pipeline.ipynb

This PR updates the Measuring Galaxy Shapes tutorial to change all references from WebbPSF to STPSF.

Update Measuring Galaxy Shapes for AAS246

---

content/notebooks/romanisim/romanisim.ipynb

This PR adds L2 source injection as an advanced use case to the Roman I-Sim tutorial. Based on a quick tutorial written up for the SNe Cosmology PIT.

Add L2 source injection

---

content/notebooks/stpsf/stpsf.ipynb

Updated notebook to use monochromatic PSFs for speed and gave instructions about polychromatic PSFs. Updated plots for PSF grids and gave evaluate example.

Updated notebook with feedback from CP

---

content/notebooks/synphot/synphot.ipynb

Updated star model to a Phoenix model with the correct parameters. This is easier to understand than the file path to a FITS file.

Updated star to Phoenix model
